apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gows-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: gows.caryqy.top-tls
      hosts:
        - "gows.caryqy.top"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gows
spec:
  hosts:
    - "*"
  gateways:
    - gows-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: gows
          weight: 100
